id: ACD2B1C10
title: Toh_308-Questions%20Regarding%20Death%20and%20Transmigration-v2
type: translation
pechas:
- I55EE7517
- I80996E9E
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-072-008
  title: Toh_308-Questions%20Regarding%20Death%20and%20Transmigration-v2
alignment_to_base:
  I55EE7517/90C0: CE96
  I80996E9E/42E8: CE96
